### ISSUE TITLE
Train loss

### ISSUE THREAD

**Issue by ds-giao** [liyuke65535/Style-Controllable-Generalized-Person-Re-identification#1]
博主你好，当我在训练Market1501->Duke时，前两个epoch没有出问题，在第三个epoch时，log_probs = nn.LogSoftmax(1)(s)出现了问题，如下所示：
2023-12-13 21:51:55,451 reid.train INFO: Epoch[3] Iteration[60/186] Loss: 8.489, id:0.000, id_dis:6.277, tri:1.833, cen:0.378  Acc: 0.002, Base Lr: 6.04e-04
2023-12-13 21:52:07,977 reid.train INFO: Epoch[3] Iteration[120/186] Loss: 8.182, id:0.000, id_dis:6.223, tri:1.611, cen:0.348  Acc: 0.002, Base Lr: 6.04e-04
Traceback (most recent call last):
  File "/home/u202232803047/test/reid/train.py", line 86, in <module>
    mix_vit_do_train_with_amp(
  File "/home/u202232803047/test/reid/processor/mix_vit_processor.py", line 109, in mix_vit_do_train_with_amp
    log_probs = nn.LogSoftmax(1)(s)
  File "/home/u202232803047/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/u202232803047/.local/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1553, in forward
    return F.log_softmax(input, self.dim, _stacklevel=5)
  File "/home/u202232803047/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 1932, in log_softmax
    ret = input.log_softmax(dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
请问您训练的时候遇到这个问题了吗，是因为代码中对单源设置出错了吗？

**Comment by liyuke65535** [comment]
Sorry for the late reply.

I find some error in "processor/mix_vit_processor.py", line 108; and "model/make_model/py", line 478
```
idx = torch.nonzero(t_domains==i).squeeze() => idx = torch.nonzero(t_domains==i).squeeze(1)
```
I've modified the code. Please pull it and try again.

**Comment by ds-giao** [comment]
> Sorry for the late reply.
> 
> I find some error in "processor/mix_vit_processor.py", line 108; and "model/make_model/py", line 478
> 
> ```
> idx = torch.nonzero(t_domains==i).squeeze() => idx = torch.nonzero(t_domains==i).squeeze(1)
> ```
> 
> I've modified the code. Please pull it and try again.

Thank you very much for your response; the issue has been successfully resolved. However, I have a question: why did the problem arise with nn.LogSoftmax(1)(s), and how does modifying the line above it with squeeze(1) solve it? These two, in my view, seem unrelated. Moreover, shouldn't squeeze(1) and squeeze() have the same effect on a tensor of size (64, 1)? What is the underlying principle?
